CREATE DATABASE db_ecommerce

USE db_ecommerce

CREATE TABLE Usuarios(
Id INT PRIMARY KEY NOT NULL,
Nome VARCHAR (50) NOT NULL,
Email VARCHAR(50) NOT NULL,
Senha VARCHAR(50) NOT NULL,
Endereco VARCHAR(100) NOT NULL
)
CREATE TABLE Produtos(
Id INT PRIMARY KEY IDENTITY NOT NULL,
NomeProduto VARCHAR(50) NOT NULL,
Descricao VARCHAR(150) NOT NULL,
Preco FLOAT NOT NULL,
FK_Criador INT NOT NULL,
FOREIGN KEY (FK_Criador) REFERENCES Usuarios (Id)
)
CREATE TABLE Compras(
FK_Comprador INT NOT NULL,
FOREIGN KEY (FK_Comprador) REFERENCES Usuarios (Id)
)